### ISSUE TITLE
[0.5pt]  Create schema for item.

### ISSUE THREAD

**Issue by worashf** [chumaachike/catalog-of-things#18]
Create a schema.sql file with tables that will be analogical to the structure of the classes in your app. As you cannot implement inheritance in the database tables - add all properties and associations from the parent Item class as table columns to all tables based on the child classes. Thanks to that it can be used to store data in the future.

**Comment by Emmykage** [comment]
Create a schema.sql file with tables that will be analogical to the structure of the classes in your app. As you cannot implement inheritance in the database tables - add all properties and associations from the parent Item class as table columns to all tables based on the child classes. Thanks to that it can be used to store data in the future.
